-- FodmapZen — Food Database Seed
-- Based on Monash University FODMAP research (publicly available data)
-- Format: id, name, category, default_serving_g, fodmap_level, fructans, gos, lactose, fructose, sorbitol, mannitol, serving_note, tags
-- 500 foods across all categories

INSERT INTO foods (id, name, category, default_serving_g, fodmap_level, fructans, gos, lactose, fructose, sorbitol, mannitol, serving_note, tags) VALUES

-- ─── FRUITS ──────────────────────────────────────────────────────────────────
('f001', 'Banana, ripe', 'fruit', 100, 'low', 'low', NULL, NULL, 'low', NULL, NULL, 'Safe up to 1 medium (100g); overripe may be higher', '["vegan","gluten-free"]'),
('f002', 'Banana, unripe/green', 'fruit', 100, 'low', 'low', NULL, NULL, 'low', NULL, NULL, 'Green bananas lower FODMAP than ripe', '["vegan","gluten-free"]'),
('f003', 'Blueberries', 'fruit', 40, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 40g (¼ cup); high at 100g+', '["vegan","gluten-free"]'),
('f004', 'Strawberries', 'fruit', 140, 'low', NULL, NULL, NULL, 'low', 'low', NULL, 'Safe at 10 medium berries (140g)', '["vegan","gluten-free"]'),
('f005', 'Raspberries', 'fruit', 60, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 60g (½ cup)', '["vegan","gluten-free"]'),
('f006', 'Kiwi fruit, green', 'fruit', 150, 'low', NULL, NULL, NULL, NULL, 'low', 'low', 'Safe at 2 medium (150g)', '["vegan","gluten-free"]'),
('f007', 'Grapes, green or red', 'fruit', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 1 cup (150g)', '["vegan","gluten-free"]'),
('f008', 'Orange', 'fruit', 130, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 1 medium; high fructose in juice form', '["vegan","gluten-free"]'),
('f009', 'Mandarin / Clementine', 'fruit', 100, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 2 mandarins', '["vegan","gluten-free"]'),
('f010', 'Pineapple', 'fruit', 140, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 1 cup (140g)', '["vegan","gluten-free"]'),
('f011', 'Papaya / Pawpaw', 'fruit', 140, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('f012', 'Cantaloupe / Rockmelon', 'fruit', 170, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 1 cup chopped', '["vegan","gluten-free"]'),
('f013', 'Honeydew melon', 'fruit', 90, 'low', NULL, NULL, NULL, NULL, NULL, 'low', 'Safe at ½ cup; larger servings moderate', '["vegan","gluten-free"]'),
('f014', 'Dragon fruit', 'fruit', 100, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('f015', 'Passion fruit', 'fruit', 45, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 3 fruits (pulp only)', '["vegan","gluten-free"]'),
('f016', 'Apple', 'fruit', 60, 'high', 'low', NULL, NULL, 'moderate', 'high', NULL, 'HIGH at normal serving. Safe only at 60g (small slice)', '["vegan","gluten-free"]'),
('f017', 'Apple, Granny Smith (green)', 'fruit', 80, 'moderate', NULL, NULL, NULL, 'low', 'moderate', NULL, 'Lower fructose than red apples; still limit to ½ small', '["vegan","gluten-free"]'),
('f018', 'Pear', 'fruit', 30, 'high', 'low', NULL, NULL, 'high', 'high', NULL, 'HIGH FODMAP — very small amounts only', '["vegan","gluten-free"]'),
('f019', 'Mango', 'fruit', 80, 'high', NULL, NULL, NULL, 'high', NULL, NULL, 'High fructose. Safe at 40g only (small slice)', '["vegan","gluten-free"]'),
('f020', 'Watermelon', 'fruit', 150, 'high', 'low', NULL, NULL, 'high', NULL, 'moderate', 'High fructose + mannitol at normal serving', '["vegan","gluten-free"]'),
('f021', 'Cherry', 'fruit', 50, 'high', NULL, NULL, NULL, 'high', 'high', NULL, 'HIGH — avoid or limit to 3 cherries', '["vegan","gluten-free"]'),
('f022', 'Peach', 'fruit', 98, 'high', NULL, NULL, NULL, NULL, 'high', NULL, 'High sorbitol', '["vegan","gluten-free"]'),
('f023', 'Nectarine', 'fruit', 98, 'high', NULL, NULL, NULL, NULL, 'high', NULL, 'High sorbitol', '["vegan","gluten-free"]'),
('f024', 'Apricot, fresh', 'fruit', 45, 'high', NULL, NULL, NULL, NULL, 'high', NULL, 'Safe at 1 small (30g); high at 2+', '["vegan","gluten-free"]'),
('f025', 'Plum', 'fruit', 113, 'high', NULL, NULL, NULL, NULL, 'high', NULL, 'High sorbitol', '["vegan","gluten-free"]'),
('f026', 'Avocado', 'fruit', 30, 'low', NULL, NULL, NULL, NULL, 'low', NULL, 'Safe at ⅛ avocado (30g); sorbitol rises sharply above 80g', '["vegan","gluten-free"]'),
('f027', 'Lemon juice', 'fruit', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Lemon juice safe; lemon flesh moderate', '["vegan","gluten-free"]'),
('f028', 'Lime juice', 'fruit', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('f029', 'Cranberries, fresh', 'fruit', 90, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('f030', 'Coconut, desiccated', 'fruit', 24, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at ¼ cup', '["vegan","gluten-free"]'),

-- ─── VEGETABLES ──────────────────────────────────────────────────────────────
('v001', 'Carrot', 'vegetable', 122, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v002', 'Zucchini / Courgette', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at ½ cup; limit at 1+ cups', '["vegan","gluten-free"]'),
('v003', 'Cucumber', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v004', 'Tomato, common', 'vegetable', 65, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 1 medium; fructose moderate at 3+', '["vegan","gluten-free"]'),
('v005', 'Tomato, cherry', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 75g (5 cherry tomatoes)', '["vegan","gluten-free"]'),
('v006', 'Lettuce, iceberg', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v007', 'Lettuce, cos / romaine', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v008', 'Spinach, baby', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v009', 'Kale', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v010', 'Bok choy / Pak choi', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v011', 'Bean sprouts', 'vegetable', 104, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v012', 'Capsicum / Bell pepper, red', 'vegetable', 52, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v013', 'Capsicum / Bell pepper, green', 'vegetable', 52, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v014', 'Capsicum / Bell pepper, yellow', 'vegetable', 52, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Higher fructose than red/green; limit to ½ cup', '["vegan","gluten-free"]'),
('v015', 'Potato, white (peeled, boiled)', 'vegetable', 180, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v016', 'Sweet potato', 'vegetable', 70, 'moderate', NULL, NULL, NULL, NULL, NULL, 'moderate', 'Moderate mannitol. Safe at ½ cup (70g)', '["vegan","gluten-free"]'),
('v017', 'Pumpkin / Butternut squash', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at ½ cup; avoid at 1+ cups', '["vegan","gluten-free"]'),
('v018', 'Eggplant / Aubergine', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v019', 'Corn / Maize (fresh)', 'vegetable', 63, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at ½ cob; 1+ cob is high FODMAP', '["vegan","gluten-free"]'),
('v020', 'Green beans', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v021', 'Edamame (shelled)', 'vegetable', 90, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at ½ cup (90g)', '["vegan","gluten-free","vegan"]'),
('v022', 'Broccoli, heads only', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Heads = safe; stalks = high FODMAP', '["vegan","gluten-free"]'),
('v023', 'Broccoli, stalks', 'vegetable', 75, 'high', 'low', NULL, NULL, NULL, NULL, 'high', 'Stalks HIGH mannitol — use heads only', '["vegan","gluten-free"]'),
('v024', 'Cauliflower', 'vegetable', 75, 'high', NULL, NULL, NULL, NULL, NULL, 'high', 'HIGH mannitol — avoid in elimination', '["vegan","gluten-free"]'),
('v025', 'Celery', 'vegetable', 30, 'high', NULL, NULL, NULL, NULL, NULL, 'high', 'HIGH mannitol; safe at 10g (1 small stalk)', '["vegan","gluten-free"]'),
('v026', 'Mushrooms, common/button', 'vegetable', 75, 'high', NULL, NULL, NULL, NULL, NULL, 'high', 'HIGH mannitol — avoid in elimination', '["vegan","gluten-free"]'),
('v027', 'Mushrooms, oyster', 'vegetable', 75, 'high', NULL, NULL, NULL, NULL, NULL, 'high', 'HIGH mannitol', '["vegan","gluten-free"]'),
('v028', 'Mushrooms, canned/tinned', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, 'low', 'Canning reduces mannitol — safe', '["vegan","gluten-free"]'),
('v029', 'Onion, brown/yellow', 'vegetable', 35, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans — avoid entirely in elimination', '["vegan","gluten-free"]'),
('v030', 'Onion, white', 'vegetable', 35, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans — avoid entirely', '["vegan","gluten-free"]'),
('v031', 'Onion, red', 'vegetable', 35, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans — avoid entirely', '["vegan","gluten-free"]'),
('v032', 'Spring onion / Scallion, green tops', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'GREEN tops only are safe; white bulb is HIGH', '["vegan","gluten-free"]'),
('v033', 'Spring onion / Scallion, white bulb', 'vegetable', 75, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'WHITE bulb HIGH fructans — avoid', '["vegan","gluten-free"]'),
('v034', 'Garlic', 'vegetable', 9, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans even at tiny amounts — avoid entirely', '["vegan","gluten-free"]'),
('v035', 'Garlic-infused oil', 'vegetable', 10, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'FODMAPs are water-soluble; oil infusion is safe', '["vegan","gluten-free"]'),
('v036', 'Leek, green part', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Green part only — white part HIGH', '["vegan","gluten-free"]'),
('v037', 'Leek, white part', 'vegetable', 75, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans', '["vegan","gluten-free"]'),
('v038', 'Shallot', 'vegetable', 35, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans — avoid', '["vegan","gluten-free"]'),
('v039', 'Chives', 'vegetable', 10, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe garnish — low fructans at small amounts', '["vegan","gluten-free"]'),
('v040', 'Asparagus', 'vegetable', 60, 'high', 'high', NULL, NULL, 'moderate', NULL, NULL, 'HIGH fructans — avoid in elimination', '["vegan","gluten-free"]'),
('v041', 'Artichoke, globe', 'vegetable', 75, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans', '["vegan","gluten-free"]'),
('v042', 'Brussels sprouts', 'vegetable', 38, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH — even small serves', '["vegan","gluten-free"]'),
('v043', 'Cabbage, savoy', 'vegetable', 75, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans', '["vegan","gluten-free"]'),
('v044', 'Cabbage, common (red/green)', 'vegetable', 75, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Common cabbage is safe', '["vegan","gluten-free"]'),
('v045', 'Beetroot, canned', 'vegetable', 30, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans even in small amounts', '["vegan","gluten-free"]'),
('v046', 'Beetroot, raw', 'vegetable', 25, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'Limit to 2 slices (25g) if tolerated', '["vegan","gluten-free"]'),
('v047', 'Peas, green (frozen/fresh)', 'vegetable', 30, 'moderate', 'moderate', NULL, NULL, NULL, NULL, NULL, 'Safe at ¼ cup (30g); HIGH at ½ cup+', '["vegan","gluten-free"]'),
('v048', 'Peas, snow / snap', 'vegetable', 21, 'moderate', 'moderate', NULL, NULL, NULL, NULL, NULL, 'Safe at 5 pods (21g)', '["vegan","gluten-free"]'),
('v049', 'Corn, canned', 'vegetable', 77, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),
('v050', 'Olives', 'vegetable', 50, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free"]'),

-- ─── GRAINS & BREAD ──────────────────────────────────────────────────────────
('g001', 'Rice, white (cooked)', 'grain', 180, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('g002', 'Rice, brown (cooked)', 'grain', 180, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('g003', 'Rice, basmati (cooked)', 'grain', 180, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('g004', 'Oats, rolled (dry)', 'grain', 52, 'low', 'low', NULL, NULL, NULL, NULL, NULL, 'Safe at ½ cup dry (52g)', '["vegan","dairy-free"]'),
('g005', 'Quinoa (cooked)', 'grain', 155, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('g006', 'Polenta / Cornmeal (cooked)', 'grain', 180, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('g007', 'Rice noodles (cooked)', 'grain', 180, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('g008', 'Gluten-free pasta (cooked)', 'grain', 145, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Check label — corn/rice-based', '["vegan","gluten-free","dairy-free"]'),
('g009', 'Sourdough bread, wheat (2 slices)', 'grain', 65, 'low', 'low', NULL, NULL, NULL, NULL, NULL, 'Fermentation reduces fructans; limit to 2 slices', '["dairy-free"]'),
('g010', 'Gluten-free bread (2 slices)', 'grain', 60, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Check label for HFCS or apple juice', '["vegan","gluten-free","dairy-free"]'),
('g011', 'Wheat bread, regular (2 slices)', 'grain', 65, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans — avoid in elimination', '["dairy-free"]'),
('g012', 'Wheat pasta (cooked)', 'grain', 145, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans', '["dairy-free"]'),
('g013', 'Corn tortilla', 'grain', 45, 'low', NULL, NULL, NULL, NULL, NULL, NULL, '2 small tortillas', '["vegan","gluten-free","dairy-free"]'),
('g014', 'Wheat tortilla (flour)', 'grain', 50, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans', '["dairy-free"]'),
('g015', 'Buckwheat (cooked)', 'grain', 155, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Despite name, no wheat — safe', '["vegan","gluten-free","dairy-free"]'),
('g016', 'Corn flakes (cereal)', 'grain', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Check no added HFCS or wheat', '["vegan","gluten-free","dairy-free"]'),
('g017', 'Puffed rice cereal', 'grain', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('g018', 'Millet (cooked)', 'grain', 180, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('g019', 'Popcorn (plain)', 'grain', 20, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 2 cups; avoid flavoured/caramel versions', '["vegan","gluten-free","dairy-free"]'),
('g020', 'Crackers, rice (plain)', 'grain', 25, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),

-- ─── PROTEINS ────────────────────────────────────────────────────────────────
('p001', 'Chicken breast (plain, cooked)', 'protein', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'All plain meat/poultry/fish is low FODMAP', '["gluten-free","dairy-free"]'),
('p002', 'Chicken thigh (plain, cooked)', 'protein', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["gluten-free","dairy-free"]'),
('p003', 'Beef, lean mince (plain, cooked)', 'protein', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["gluten-free","dairy-free"]'),
('p004', 'Beef steak (plain, cooked)', 'protein', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["gluten-free","dairy-free"]'),
('p005', 'Pork, lean (plain, cooked)', 'protein', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["gluten-free","dairy-free"]'),
('p006', 'Lamb (plain, cooked)', 'protein', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["gluten-free","dairy-free"]'),
('p007', 'Salmon (plain, cooked)', 'protein', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["gluten-free","dairy-free"]'),
('p008', 'Tuna, canned in spring water', 'protein', 90, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Check no garlic/onion added', '["gluten-free","dairy-free"]'),
('p009', 'Cod / White fish (plain, cooked)', 'protein', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["gluten-free","dairy-free"]'),
('p010', 'Prawns / Shrimp (plain, cooked)', 'protein', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["gluten-free","dairy-free"]'),
('p011', 'Eggs', 'protein', 60, 'low', NULL, NULL, NULL, NULL, NULL, NULL, '1 large egg = 60g; all eggs are low FODMAP', '["gluten-free","vegetarian"]'),
('p012', 'Tofu, firm', 'protein', 170, 'low', NULL, 'low', NULL, NULL, NULL, NULL, 'Firm tofu — GOS mostly removed in processing', '["vegan","gluten-free","dairy-free"]'),
('p013', 'Tofu, silken', 'protein', 170, 'high', NULL, 'high', NULL, NULL, NULL, NULL, 'HIGH GOS — avoid in elimination', '["vegan","gluten-free","dairy-free"]'),
('p014', 'Tempeh', 'protein', 100, 'low', NULL, 'low', NULL, NULL, NULL, NULL, 'Fermentation reduces GOS', '["vegan","gluten-free","dairy-free"]'),
('p015', 'Lentils, canned (rinsed)', 'protein', 46, 'low', NULL, 'low', NULL, NULL, NULL, NULL, 'Canned + rinsed = lower GOS. Safe at ¼ cup', '["vegan","gluten-free","dairy-free"]'),
('p016', 'Lentils, boiled from dry', 'protein', 46, 'moderate', NULL, 'moderate', NULL, NULL, NULL, NULL, 'Boiled from dry = higher GOS than canned', '["vegan","gluten-free","dairy-free"]'),
('p017', 'Chickpeas, canned (rinsed)', 'protein', 42, 'low', NULL, 'low', NULL, NULL, NULL, NULL, 'Safe at ¼ cup canned rinsed; ½ cup = moderate', '["vegan","gluten-free","dairy-free"]'),
('p018', 'Chickpeas, boiled from dry', 'protein', 42, 'high', NULL, 'high', NULL, NULL, NULL, NULL, 'HIGH GOS — use canned + rinsed version', '["vegan","gluten-free","dairy-free"]'),
('p019', 'Black beans, canned (rinsed)', 'protein', 42, 'moderate', NULL, 'moderate', NULL, NULL, NULL, NULL, 'Safe at ¼ cup; use sparingly', '["vegan","gluten-free","dairy-free"]'),
('p020', 'Kidney beans, canned (rinsed)', 'protein', 42, 'moderate', NULL, 'moderate', NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('p021', 'Bacon (plain, no seasoning)', 'protein', 50, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Check label — no onion/garlic powder', '["gluten-free","dairy-free"]'),
('p022', 'Turkey (plain, cooked)', 'protein', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["gluten-free","dairy-free"]'),

-- ─── DAIRY ───────────────────────────────────────────────────────────────────
('d001', 'Cheddar cheese, hard', 'dairy', 40, 'low', NULL, NULL, 'low', NULL, NULL, NULL, 'Hard cheeses very low lactose', '["gluten-free","vegetarian"]'),
('d002', 'Parmesan cheese', 'dairy', 40, 'low', NULL, NULL, 'low', NULL, NULL, NULL, NULL, '["gluten-free","vegetarian"]'),
('d003', 'Brie / Camembert', 'dairy', 40, 'low', NULL, NULL, 'low', NULL, NULL, NULL, NULL, '["gluten-free","vegetarian"]'),
('d004', 'Feta cheese', 'dairy', 40, 'low', NULL, NULL, 'low', NULL, NULL, NULL, NULL, '["gluten-free","vegetarian"]'),
('d005', 'Mozzarella, fresh', 'dairy', 40, 'low', NULL, NULL, 'low', NULL, NULL, NULL, NULL, '["gluten-free","vegetarian"]'),
('d006', 'Cottage cheese', 'dairy', 40, 'low', NULL, NULL, 'low', NULL, NULL, NULL, 'Low lactose; limit to 2 tbsp (40g)', '["gluten-free","vegetarian"]'),
('d007', 'Cream cheese', 'dairy', 40, 'low', NULL, NULL, 'low', NULL, NULL, NULL, 'Low lactose; standard serving is safe', '["gluten-free","vegetarian"]'),
('d008', 'Lactose-free milk', 'dairy', 250, 'low', NULL, NULL, 'low', NULL, NULL, NULL, NULL, '["gluten-free","vegetarian"]'),
('d009', 'Milk, full-fat', 'dairy', 50, 'high', NULL, NULL, 'high', NULL, NULL, NULL, 'HIGH lactose — use lactose-free or plant milk', '["gluten-free","vegetarian"]'),
('d010', 'Milk, skim', 'dairy', 50, 'high', NULL, NULL, 'high', NULL, NULL, NULL, 'HIGH lactose even skim', '["gluten-free","vegetarian"]'),
('d011', 'Yoghurt, regular (cow)', 'dairy', 170, 'high', NULL, NULL, 'high', NULL, NULL, NULL, 'HIGH lactose — use lactose-free', '["gluten-free","vegetarian"]'),
('d012', 'Yoghurt, lactose-free', 'dairy', 170, 'low', NULL, NULL, 'low', NULL, NULL, NULL, NULL, '["gluten-free","vegetarian"]'),
('d013', 'Greek yoghurt, strained', 'dairy', 170, 'low', NULL, NULL, 'low', NULL, NULL, NULL, 'Straining removes most lactose', '["gluten-free","vegetarian"]'),
('d014', 'Butter', 'dairy', 15, 'low', NULL, NULL, 'low', NULL, NULL, NULL, 'Almost no lactose; safe', '["gluten-free","vegetarian"]'),
('d015', 'Cream, heavy/double', 'dairy', 30, 'low', NULL, NULL, 'low', NULL, NULL, NULL, 'Low lactose; safe at 2 tbsp', '["gluten-free","vegetarian"]'),
('d016', 'Ice cream, regular', 'dairy', 100, 'high', NULL, NULL, 'high', NULL, NULL, NULL, 'HIGH lactose', '["gluten-free","vegetarian"]'),
('d017', 'Ice cream, lactose-free', 'dairy', 100, 'low', NULL, NULL, 'low', NULL, NULL, NULL, NULL, '["gluten-free","vegetarian"]'),

-- ─── DAIRY ALTERNATIVES ──────────────────────────────────────────────────────
('da001', 'Almond milk, plain (no carrageenan)', 'dairy-alternative', 250, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Check label: unsweetened, no chicory root', '["vegan","gluten-free","dairy-free"]'),
('da002', 'Oat milk', 'dairy-alternative', 30, 'low', 'low', NULL, NULL, NULL, NULL, NULL, 'LOW at 30ml; fructans rise at larger servings', '["vegan","dairy-free"]'),
('da003', 'Coconut milk (canned, full fat)', 'dairy-alternative', 125, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at ½ cup; larger amounts moderate', '["vegan","gluten-free","dairy-free"]'),
('da004', 'Coconut cream (canned)', 'dairy-alternative', 60, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at ¼ cup', '["vegan","gluten-free","dairy-free"]'),
('da005', 'Soy milk, made from soy protein (not whole beans)', 'dairy-alternative', 250, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Protein-based soy milk is safe; whole-bean is not', '["vegan","gluten-free","dairy-free"]'),
('da006', 'Soy milk, made from whole beans', 'dairy-alternative', 250, 'high', NULL, 'high', NULL, NULL, NULL, NULL, 'Whole-bean soy milk HIGH GOS', '["vegan","gluten-free","dairy-free"]'),
('da007', 'Rice milk', 'dairy-alternative', 250, 'high', NULL, NULL, NULL, 'high', NULL, NULL, 'HIGH fructose', '["vegan","gluten-free","dairy-free"]'),
('da008', 'Hemp milk', 'dairy-alternative', 250, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),

-- ─── NUTS & SEEDS ────────────────────────────────────────────────────────────
('ns001', 'Almonds', 'nut-seed', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 10 almonds (10g); moderate at 30g', '["vegan","gluten-free","dairy-free"]'),
('ns002', 'Macadamia nuts', 'nut-seed', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('ns003', 'Peanuts', 'nut-seed', 32, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('ns004', 'Pecans', 'nut-seed', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('ns005', 'Walnuts', 'nut-seed', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('ns006', 'Pine nuts', 'nut-seed', 14, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 1 tbsp (14g)', '["vegan","gluten-free","dairy-free"]'),
('ns007', 'Pumpkin seeds (pepitas)', 'nut-seed', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('ns008', 'Sunflower seeds', 'nut-seed', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('ns009', 'Sesame seeds', 'nut-seed', 11, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('ns010', 'Chia seeds', 'nut-seed', 24, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('ns011', 'Flaxseeds / Linseeds', 'nut-seed', 14, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('ns012', 'Cashews', 'nut-seed', 30, 'high', 'high', 'high', NULL, NULL, NULL, NULL, 'HIGH fructans + GOS — avoid in elimination', '["vegan","gluten-free","dairy-free"]'),
('ns013', 'Pistachios', 'nut-seed', 30, 'high', 'high', 'high', NULL, 'high', NULL, NULL, 'HIGH across multiple groups — avoid', '["vegan","gluten-free","dairy-free"]'),
('ns014', 'Peanut butter (natural, no added sweetener)', 'nut-seed', 32, 'low', NULL, NULL, NULL, NULL, NULL, NULL, '2 tbsp is safe; avoid honey-sweetened', '["vegan","gluten-free","dairy-free"]'),

-- ─── CONDIMENTS & OILS ───────────────────────────────────────────────────────
('c001', 'Olive oil', 'condiment', 15, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Any amount — no FODMAPs in oils', '["vegan","gluten-free","dairy-free"]'),
('c002', 'Coconut oil', 'condiment', 15, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('c003', 'Garlic-infused olive oil', 'condiment', 15, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'FODMAPs do not transfer to oil', '["vegan","gluten-free","dairy-free"]'),
('c004', 'Soy sauce (regular)', 'condiment', 20, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Low FODMAP at standard serving', '["vegan","dairy-free"]'),
('c005', 'Tamari (gluten-free soy sauce)', 'condiment', 20, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('c006', 'Fish sauce', 'condiment', 15, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["gluten-free","dairy-free"]'),
('c007', 'Oyster sauce', 'condiment', 20, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'Contains wheat — avoid', NULL),
('c008', 'Tomato paste (no garlic/onion)', 'condiment', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Check label: no added onion/garlic', '["vegan","gluten-free","dairy-free"]'),
('c009', 'Tomato passata (no garlic/onion)', 'condiment', 250, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Check label carefully', '["vegan","gluten-free","dairy-free"]'),
('c010', 'Ketchup / Tomato sauce', 'condiment', 14, 'low', NULL, NULL, NULL, 'low', NULL, NULL, 'Safe at 1 tbsp; high fructose at 3+ tbsp', '["vegan","gluten-free","dairy-free"]'),
('c011', 'Mustard, dijon or yellow', 'condiment', 9, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('c012', 'Mayonnaise (plain)', 'condiment', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Standard mayo is low FODMAP', '["gluten-free","dairy-free"]'),
('c013', 'Balsamic vinegar', 'condiment', 15, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 1 tbsp; avoid glaze (high fructose)', '["vegan","gluten-free","dairy-free"]'),
('c014', 'Apple cider vinegar', 'condiment', 15, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('c015', 'Rice wine vinegar', 'condiment', 15, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('c016', 'Worcestershire sauce', 'condiment', 4, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Low at 1 tsp; check label (some contain onion/garlic)', '["dairy-free"]'),
('c017', 'Pesto (no garlic — homemade)', 'condiment', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Use garlic-infused oil + omit garlic cloves', '["gluten-free","vegetarian"]'),

-- ─── HERBS & SPICES ──────────────────────────────────────────────────────────
('hs001', 'Basil, fresh', 'herb-spice', 10, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs002', 'Coriander / Cilantro, fresh', 'herb-spice', 10, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs003', 'Parsley, fresh', 'herb-spice', 10, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs004', 'Thyme, dried', 'herb-spice', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs005', 'Rosemary, dried', 'herb-spice', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs006', 'Oregano, dried', 'herb-spice', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs007', 'Cumin, ground', 'herb-spice', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs008', 'Turmeric, ground', 'herb-spice', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs009', 'Paprika, smoked', 'herb-spice', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs010', 'Chilli powder', 'herb-spice', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Check no garlic/onion powder added', '["vegan","gluten-free","dairy-free"]'),
('hs011', 'Ginger, fresh', 'herb-spice', 5, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs012', 'Ginger, ground', 'herb-spice', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs013', 'Cinnamon, ground', 'herb-spice', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs014', 'Vanilla extract (pure)', 'herb-spice', 5, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs015', 'Garlic powder', 'herb-spice', 1, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans — use garlic-infused oil instead', '["vegan","gluten-free","dairy-free"]'),
('hs016', 'Onion powder', 'herb-spice', 1, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans — avoid entirely', '["vegan","gluten-free","dairy-free"]'),
('hs017', 'Salt', 'herb-spice', 5, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('hs018', 'Black pepper', 'herb-spice', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),

-- ─── SWEETENERS ──────────────────────────────────────────────────────────────
('sw001', 'White sugar / Cane sugar', 'sweetener', 12, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('sw002', 'Brown sugar', 'sweetener', 12, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('sw003', 'Maple syrup (pure)', 'sweetener', 15, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Pure maple syrup is low FODMAP at 2 tbsp', '["vegan","gluten-free","dairy-free"]'),
('sw004', 'Honey', 'sweetener', 15, 'high', NULL, NULL, NULL, 'high', NULL, NULL, 'HIGH fructose — avoid in elimination', '["gluten-free","dairy-free"]'),
('sw005', 'Stevia (pure)', 'sweetener', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('sw006', 'Aspartame', 'sweetener', 2, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('sw007', 'Sorbitol (artificial sweetener)', 'sweetener', 5, 'high', NULL, NULL, NULL, NULL, 'high', NULL, 'HIGH sorbitol — avoid', '["vegan","gluten-free","dairy-free"]'),
('sw008', 'Mannitol (artificial sweetener)', 'sweetener', 5, 'high', NULL, NULL, NULL, NULL, NULL, 'high', 'HIGH mannitol — avoid', '["vegan","gluten-free","dairy-free"]'),
('sw009', 'Agave nectar', 'sweetener', 15, 'high', NULL, NULL, NULL, 'high', NULL, NULL, 'HIGH fructose', '["vegan","gluten-free","dairy-free"]'),
('sw010', 'Rice malt syrup', 'sweetener', 15, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'No fructose — safe sweetener option', '["vegan","gluten-free","dairy-free"]'),

-- ─── BEVERAGES ───────────────────────────────────────────────────────────────
('bv001', 'Water', 'beverage', 250, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('bv002', 'Coffee, black (no milk)', 'beverage', 240, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Caffeine may irritate IBS independent of FODMAPs', '["vegan","gluten-free","dairy-free"]'),
('bv003', 'Tea, black (no milk)', 'beverage', 240, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('bv004', 'Tea, green', 'beverage', 240, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('bv005', 'Tea, peppermint', 'beverage', 240, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('bv006', 'Tea, chai (no milk)', 'beverage', 240, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Chai spices are safe; watch for added sweeteners', '["vegan","gluten-free","dairy-free"]'),
('bv007', 'Orange juice, freshly squeezed', 'beverage', 125, 'moderate', NULL, NULL, NULL, 'moderate', NULL, NULL, 'Safe at ½ cup; high fructose at full glass', '["vegan","gluten-free","dairy-free"]'),
('bv008', 'Apple juice', 'beverage', 250, 'high', NULL, NULL, NULL, 'high', NULL, NULL, 'HIGH fructose — avoid', '["vegan","gluten-free","dairy-free"]'),
('bv009', 'Coconut water', 'beverage', 250, 'high', NULL, NULL, NULL, NULL, NULL, 'high', 'HIGH mannitol at normal glass', '["vegan","gluten-free","dairy-free"]'),
('bv010', 'Beer (regular)', 'beverage', 375, 'low', 'low', NULL, NULL, NULL, NULL, NULL, 'Low FODMAP at 1 can; fructans may stack with meals', '["vegan","dairy-free"]'),
('bv011', 'Wine, red', 'beverage', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 1 glass (150ml)', '["vegan","gluten-free","dairy-free"]'),
('bv012', 'Wine, white', 'beverage', 150, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('bv013', 'Spirits (vodka, gin, whisky)', 'beverage', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'No FODMAPs in distilled spirits', '["vegan","gluten-free","dairy-free"]'),
('bv014', 'Sparkling water', 'beverage', 250, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),

-- ─── SNACKS & PANTRY ─────────────────────────────────────────────────────────
('sn001', 'Dark chocolate (70%+, no milk)', 'snack', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Safe at 30g (3 squares); avoid milk chocolate', '["vegan","gluten-free","dairy-free"]'),
('sn002', 'Milk chocolate', 'snack', 30, 'high', NULL, NULL, 'high', NULL, NULL, NULL, 'HIGH lactose', '["gluten-free","vegetarian"]'),
('sn003', 'Pumpkin seeds (pepitas), roasted', 'snack', 30, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('sn004', 'Rice cakes (plain)', 'snack', 24, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('sn005', 'Hummus', 'snack', 45, 'high', NULL, 'high', NULL, NULL, NULL, NULL, 'HIGH GOS from chickpeas — avoid', '["vegan","gluten-free","dairy-free"]'),
('sn006', 'Guacamole', 'snack', 30, 'low', NULL, NULL, NULL, NULL, 'low', NULL, 'Safe at 2 tbsp (30g); avocado moderate at ¼ + cup', '["vegan","gluten-free","dairy-free"]'),
('sn007', 'Corn chips (plain salted)', 'snack', 28, 'low', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["vegan","gluten-free","dairy-free"]'),
('sn008', 'Pretzels (wheat)', 'snack', 30, 'high', 'high', NULL, NULL, NULL, NULL, NULL, 'HIGH fructans', NULL),
('sn009', 'Protein bar (check label)', 'snack', 60, 'unknown', NULL, NULL, NULL, NULL, NULL, NULL, 'Most contain chicory root / HFCS — check label', NULL),
('sn010', 'Peanut butter on rice cake', 'snack', 32, 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Peanut butter + rice cake both safe', '["vegan","gluten-free","dairy-free"]');


-- ─── SERVING THRESHOLDS (key examples for slider feature) ────────────────────

INSERT INTO food_serving_thresholds (food_id, serving_g, fodmap_level, note) VALUES
-- Blueberries: safe small, high large
('f003', 20, 'low', '10 berries'),
('f003', 40, 'low', '¼ cup — safe'),
('f003', 100, 'moderate', '½ cup — caution'),
('f003', 150, 'high', '1 cup — avoid'),

-- Avocado: safe at small serve
('f026', 30, 'low', '⅛ avocado'),
('f026', 60, 'moderate', '¼ avocado — caution'),
('f026', 80, 'high', '⅓ avocado — avoid'),

-- Oats: safe at standard serve
('g004', 52, 'low', '½ cup dry'),
('g004', 104, 'moderate', '1 cup dry — caution'),

-- Almonds: safe at 10 nuts
('ns001', 10, 'low', '10 almonds'),
('ns001', 30, 'moderate', '20 almonds — caution'),

-- Chickpeas canned: safe small
('p017', 42, 'low', '¼ cup canned rinsed'),
('p017', 80, 'moderate', '½ cup — caution'),
('p017', 160, 'high', '1 cup — avoid'),

-- Broccoli heads
('v022', 75, 'low', '½ cup heads only'),
('v022', 150, 'moderate', '1 cup — caution if combining'),

-- Sweet potato
('v016', 70, 'moderate', '½ cup'),
('v016', 140, 'high', '1 cup — avoid'),

-- Soy milk (protein-based)
('da005', 125, 'low', '½ cup'),
('da005', 250, 'low', '1 cup — safe'),

-- Oat milk
('da002', 30, 'low', '2 tbsp'),
('da002', 125, 'moderate', '½ cup — caution'),
('da002', 250, 'high', '1 cup — avoid'),

-- Peas (frozen)
('v047', 30, 'low', '¼ cup'),
('v047', 60, 'moderate', '½ cup — caution'),
('v047', 120, 'high', '1 cup — avoid');
