// Starter recipe seed — low-FODMAP, dietitian-style portions.
// Serving sizes follow Monash/FODMAP Friendly thresholds. Garlic/onion are
// always replaced with garlic-infused oil and the green tops of spring onion.

export const RECIPES_SEED_SQL = `
INSERT INTO recipes (id, title, description, meal_type, prep_mins, cook_mins, default_servings, difficulty, calories, protein_g, carbs_g, fat_g, fibre_g, is_premium, phase_compatible, dietitian_verified, created_at) VALUES
('r001', 'Spinach & Feta Omelette', 'A fluffy two-egg omelette with wilted spinach and a little lactose-free feta. Ready in 10 minutes.', 'breakfast', 5, 8, 1, 'easy', 320, 22, 4, 24, 2, 0, '["elimination","reintroduction","maintenance"]', 1, datetime('now')),
('r002', 'Overnight Oats with Berries', 'Creamy lactose-free overnight oats topped with blueberries and strawberries. Prep the night before.', 'breakfast', 5, 0, 1, 'easy', 340, 12, 52, 9, 6, 0, '["elimination","reintroduction","maintenance"]', 1, datetime('now')),
('r003', 'Banana Buckwheat Pancakes', 'Naturally gluten-free pancakes sweetened with ripe banana and maple syrup.', 'breakfast', 10, 12, 2, 'easy', 290, 9, 46, 8, 4, 0, '["elimination","reintroduction","maintenance"]', 0, datetime('now')),
('r004', 'Quinoa Tabbouleh', 'A fresh herb-packed quinoa salad with tomato, cucumber, parsley and a lemon dressing.', 'lunch', 15, 15, 2, 'easy', 280, 8, 40, 10, 6, 0, '["elimination","reintroduction","maintenance"]', 1, datetime('now')),
('r005', 'Grilled Chicken & Rice Bowl', 'Garlic-infused grilled chicken over jasmine rice with carrot and green spring-onion tops.', 'lunch', 10, 20, 2, 'easy', 420, 35, 45, 11, 3, 0, '["elimination","reintroduction","maintenance"]', 1, datetime('now')),
('r006', 'Caprese Rice Cakes', 'Quick open snack-lunch of rice cakes, tomato, lactose-free mozzarella and basil.', 'lunch', 8, 0, 1, 'easy', 240, 12, 26, 10, 2, 0, '["elimination","reintroduction","maintenance"]', 0, datetime('now')),
('r007', 'Lemon Herb Salmon', 'Oven-baked salmon fillet with lemon, dill and a drizzle of garlic-infused oil.', 'dinner', 10, 18, 2, 'easy', 410, 34, 3, 28, 1, 0, '["elimination","reintroduction","maintenance"]', 1, datetime('now')),
('r008', 'Beef & Veg Stir-Fry', 'Strips of beef with bok choy, carrot and capsicum in a ginger-soy glaze over rice.', 'dinner', 15, 12, 3, 'medium', 460, 32, 48, 15, 5, 0, '["elimination","reintroduction","maintenance"]', 1, datetime('now')),
('r009', 'Polenta with Roast Veg', 'Creamy polenta topped with roasted zucchini, capsicum and cherry tomato.', 'dinner', 15, 30, 3, 'medium', 350, 9, 52, 12, 6, 0, '["elimination","reintroduction","maintenance"]', 0, datetime('now')),
('r010', 'Peanut Butter Energy Bites', 'No-bake oat bites with peanut butter, dark chocolate chips and maple syrup.', 'snack', 15, 0, 12, 'easy', 110, 3, 12, 6, 2, 0, '["elimination","reintroduction","maintenance"]', 0, datetime('now')),
('r011', 'Carrot & Cucumber Sticks with Dip', 'Crunchy veg sticks with a lemony lactose-free yoghurt dip.', 'snack', 10, 0, 2, 'easy', 130, 6, 12, 6, 3, 0, '["elimination","reintroduction","maintenance"]', 0, datetime('now')),
('r012', 'Dark Chocolate & Strawberry Bark', 'Melted dark chocolate studded with strawberries and a pinch of sea salt.', 'dessert', 10, 0, 8, 'easy', 150, 2, 16, 9, 2, 0, '["elimination","reintroduction","maintenance"]', 0, datetime('now')),
('r013', 'Scrambled Eggs & Chive Toast', 'Soft scrambled eggs with fresh chives on toasted sourdough.', 'breakfast', 5, 5, 1, 'easy', 310, 18, 22, 16, 2, 0, '["elimination","reintroduction","maintenance"]', 1, datetime('now')),
('r014', 'Berry Chia Pudding', 'Make-ahead chia pudding with lactose-free milk and fresh berries.', 'breakfast', 5, 0, 1, 'easy', 280, 9, 30, 14, 10, 0, '["elimination","reintroduction","maintenance"]', 1, datetime('now')),
('r015', 'Tofu Rice Paper Rolls', 'Fresh rice paper rolls with firm tofu, carrot, cucumber and herbs.', 'lunch', 20, 0, 2, 'medium', 260, 14, 34, 8, 4, 0, '["elimination","reintroduction","maintenance"]', 0, datetime('now')),
('r016', 'Pumpkin & Feta Frittata', 'A baked frittata with roast pumpkin, spinach and lactose-free feta.', 'lunch', 10, 25, 4, 'easy', 240, 15, 9, 16, 2, 0, '["elimination","reintroduction","maintenance"]', 1, datetime('now')),
('r017', 'Lemon Roast Chicken & Potatoes', 'One-tray roast chicken thighs with potatoes, lemon and garlic-infused oil.', 'dinner', 15, 45, 4, 'easy', 480, 38, 32, 22, 3, 0, '["elimination","reintroduction","maintenance"]', 1, datetime('now')),
('r018', 'Prawn & Zucchini Rice', 'Quick prawn stir-fry with zucchini and ginger over jasmine rice.', 'dinner', 10, 15, 2, 'easy', 390, 28, 50, 8, 3, 0, '["elimination","reintroduction","maintenance"]', 0, datetime('now')),
('r019', 'Maple Roasted Carrots', 'Caramelised roast carrots glazed with maple syrup and thyme.', 'snack', 5, 30, 4, 'easy', 120, 1, 18, 5, 4, 0, '["elimination","reintroduction","maintenance"]', 0, datetime('now')),
('r020', 'Peanut Butter Banana Oat Cookies', 'Three-ingredient cookies with ripe banana, oats and peanut butter.', 'dessert', 10, 15, 12, 'easy', 95, 3, 12, 4, 2, 0, '["elimination","reintroduction","maintenance"]', 0, datetime('now'));

INSERT INTO recipe_ingredients (recipe_id, food_name, amount, unit, notes, is_optional, fodmap_level, sort_order) VALUES
('r001', 'Eggs', 2, 'whole', NULL, 0, 'low', 0),
('r001', 'Baby spinach', 1, 'cup', 'safe up to 75g', 0, 'low', 1),
('r001', 'Lactose-free feta', 30, 'g', NULL, 0, 'low', 2),
('r001', 'Garlic-infused olive oil', 1, 'tsp', NULL, 0, 'low', 3),
('r001', 'Salt & pepper', 1, 'pinch', NULL, 1, 'low', 4),
('r002', 'Rolled oats', 0.5, 'cup', 'safe at 1/2 cup dry', 0, 'low', 0),
('r002', 'Lactose-free milk', 0.5, 'cup', NULL, 0, 'low', 1),
('r002', 'Lactose-free natural yoghurt', 2, 'tbsp', NULL, 0, 'low', 2),
('r002', 'Blueberries', 0.25, 'cup', 'safe at 40g', 0, 'low', 3),
('r002', 'Strawberries', 5, 'whole', NULL, 0, 'low', 4),
('r002', 'Maple syrup', 1, 'tsp', NULL, 1, 'low', 5),
('r003', 'Buckwheat flour', 1, 'cup', NULL, 0, 'low', 0),
('r003', 'Ripe banana', 1, 'whole', 'safe at 1 medium', 0, 'low', 1),
('r003', 'Egg', 1, 'whole', NULL, 0, 'low', 2),
('r003', 'Lactose-free milk', 0.75, 'cup', NULL, 0, 'low', 3),
('r003', 'Baking powder', 1, 'tsp', NULL, 0, 'low', 4),
('r003', 'Maple syrup', 2, 'tbsp', 'to serve', 1, 'low', 5),
('r004', 'Quinoa', 0.5, 'cup', 'dry, rinsed', 0, 'low', 0),
('r004', 'Tomato', 1, 'whole', 'diced', 0, 'low', 1),
('r004', 'Cucumber', 0.5, 'whole', 'diced', 0, 'low', 2),
('r004', 'Fresh parsley', 1, 'cup', 'chopped', 0, 'low', 3),
('r004', 'Fresh mint', 0.25, 'cup', 'chopped', 1, 'low', 4),
('r004', 'Lemon juice', 2, 'tbsp', NULL, 0, 'low', 5),
('r004', 'Extra virgin olive oil', 2, 'tbsp', NULL, 0, 'low', 6),
('r005', 'Chicken breast', 300, 'g', NULL, 0, 'low', 0),
('r005', 'Jasmine rice', 1, 'cup', 'dry', 0, 'low', 1),
('r005', 'Carrot', 1, 'whole', 'julienned', 0, 'low', 2),
('r005', 'Spring onion (green tops only)', 2, 'stalk', NULL, 0, 'low', 3),
('r005', 'Garlic-infused olive oil', 1, 'tbsp', NULL, 0, 'low', 4),
('r005', 'Soy sauce (gluten-free)', 1, 'tbsp', NULL, 0, 'low', 5),
('r006', 'Plain rice cakes', 2, 'whole', NULL, 0, 'low', 0),
('r006', 'Tomato', 1, 'whole', 'sliced', 0, 'low', 1),
('r006', 'Lactose-free mozzarella', 40, 'g', NULL, 0, 'low', 2),
('r006', 'Fresh basil', 4, 'leaf', NULL, 0, 'low', 3),
('r006', 'Extra virgin olive oil', 1, 'tsp', NULL, 1, 'low', 4),
('r007', 'Salmon fillet', 2, 'fillet', 'approx 150g each', 0, 'low', 0),
('r007', 'Lemon', 1, 'whole', 'sliced', 0, 'low', 1),
('r007', 'Fresh dill', 2, 'tbsp', 'chopped', 0, 'low', 2),
('r007', 'Garlic-infused olive oil', 1, 'tbsp', NULL, 0, 'low', 3),
('r007', 'Salt & pepper', 1, 'pinch', NULL, 0, 'low', 4),
('r008', 'Beef rump strips', 350, 'g', NULL, 0, 'low', 0),
('r008', 'Bok choy', 2, 'cup', 'chopped', 0, 'low', 1),
('r008', 'Carrot', 1, 'whole', 'sliced', 0, 'low', 2),
('r008', 'Red capsicum', 1, 'whole', 'sliced', 0, 'low', 3),
('r008', 'Fresh ginger', 1, 'tbsp', 'grated', 0, 'low', 4),
('r008', 'Soy sauce (gluten-free)', 2, 'tbsp', NULL, 0, 'low', 5),
('r008', 'Jasmine rice', 1.5, 'cup', 'dry', 0, 'low', 6),
('r009', 'Polenta', 1, 'cup', NULL, 0, 'low', 0),
('r009', 'Zucchini', 1, 'whole', 'diced', 0, 'low', 1),
('r009', 'Red capsicum', 1, 'whole', 'diced', 0, 'low', 2),
('r009', 'Cherry tomatoes', 1, 'cup', NULL, 0, 'low', 3),
('r009', 'Parmesan', 30, 'g', 'grated', 1, 'low', 4),
('r009', 'Garlic-infused olive oil', 1, 'tbsp', NULL, 0, 'low', 5),
('r010', 'Rolled oats', 1, 'cup', NULL, 0, 'low', 0),
('r010', 'Peanut butter', 0.5, 'cup', NULL, 0, 'low', 1),
('r010', 'Maple syrup', 0.25, 'cup', NULL, 0, 'low', 2),
('r010', 'Dark chocolate chips', 0.25, 'cup', NULL, 0, 'low', 3),
('r011', 'Carrot', 2, 'whole', 'cut into sticks', 0, 'low', 0),
('r011', 'Cucumber', 1, 'whole', 'cut into sticks', 0, 'low', 1),
('r011', 'Lactose-free natural yoghurt', 0.5, 'cup', NULL, 0, 'low', 2),
('r011', 'Lemon juice', 1, 'tsp', NULL, 0, 'low', 3),
('r011', 'Fresh chives', 1, 'tbsp', 'chopped', 1, 'low', 4),
('r012', 'Dark chocolate (70%)', 200, 'g', NULL, 0, 'low', 0),
('r012', 'Strawberries', 1, 'cup', 'sliced', 0, 'low', 1),
('r012', 'Sea salt', 1, 'pinch', NULL, 1, 'low', 2),
('r013', 'Eggs', 2, 'whole', NULL, 0, 'low', 0),
('r013', 'Lactose-free milk', 1, 'tbsp', NULL, 0, 'low', 1),
('r013', 'Sourdough spelt bread', 1, 'slice', NULL, 0, 'low', 2),
('r013', 'Fresh chives', 1, 'tbsp', 'chopped', 0, 'low', 3),
('r013', 'Butter', 1, 'tsp', NULL, 1, 'low', 4),
('r013', 'Salt & pepper', 1, 'pinch', NULL, 0, 'low', 5),
('r014', 'Chia seeds', 3, 'tbsp', NULL, 0, 'low', 0),
('r014', 'Lactose-free milk', 0.75, 'cup', NULL, 0, 'low', 1),
('r014', 'Maple syrup', 1, 'tsp', NULL, 1, 'low', 2),
('r014', 'Blueberries', 0.25, 'cup', NULL, 0, 'low', 3),
('r014', 'Strawberries', 4, 'whole', 'sliced', 0, 'low', 4),
('r015', 'Rice paper wrappers', 6, 'sheet', NULL, 0, 'low', 0),
('r015', 'Firm tofu', 150, 'g', 'sliced into strips', 0, 'low', 1),
('r015', 'Carrot', 1, 'whole', 'julienned', 0, 'low', 2),
('r015', 'Cucumber', 0.5, 'whole', 'julienned', 0, 'low', 3),
('r015', 'Fresh mint', 0.25, 'cup', NULL, 0, 'low', 4),
('r015', 'Rice vermicelli', 50, 'g', 'cooked', 0, 'low', 5),
('r015', 'Tamari (gluten-free)', 2, 'tbsp', 'to serve', 1, 'low', 6),
('r016', 'Eggs', 6, 'whole', NULL, 0, 'low', 0),
('r016', 'Pumpkin', 200, 'g', 'diced, roasted', 0, 'low', 1),
('r016', 'Baby spinach', 1, 'cup', NULL, 0, 'low', 2),
('r016', 'Lactose-free feta', 60, 'g', 'crumbled', 0, 'low', 3),
('r016', 'Garlic-infused olive oil', 1, 'tbsp', NULL, 0, 'low', 4),
('r016', 'Spring onion (green tops only)', 2, 'stalk', NULL, 0, 'low', 5),
('r017', 'Chicken thighs', 8, 'piece', 'bone-in', 0, 'low', 0),
('r017', 'Potatoes', 600, 'g', 'quartered', 0, 'low', 1),
('r017', 'Lemon', 1, 'whole', 'cut into wedges', 0, 'low', 2),
('r017', 'Garlic-infused olive oil', 2, 'tbsp', NULL, 0, 'low', 3),
('r017', 'Fresh rosemary', 2, 'sprig', NULL, 0, 'low', 4),
('r017', 'Salt & pepper', 1, 'pinch', NULL, 0, 'low', 5),
('r018', 'Raw prawns, peeled', 250, 'g', NULL, 0, 'low', 0),
('r018', 'Zucchini', 1, 'whole', 'diced', 0, 'low', 1),
('r018', 'Jasmine rice', 1, 'cup', 'dry', 0, 'low', 2),
('r018', 'Fresh ginger', 1, 'tbsp', 'grated', 0, 'low', 3),
('r018', 'Garlic-infused olive oil', 1, 'tbsp', NULL, 0, 'low', 4),
('r018', 'Soy sauce (gluten-free)', 1, 'tbsp', NULL, 0, 'low', 5),
('r019', 'Carrots', 6, 'whole', 'halved lengthways', 0, 'low', 0),
('r019', 'Maple syrup', 1, 'tbsp', NULL, 0, 'low', 1),
('r019', 'Olive oil', 1, 'tbsp', NULL, 0, 'low', 2),
('r019', 'Fresh thyme', 1, 'tsp', NULL, 1, 'low', 3),
('r020', 'Ripe banana', 2, 'whole', 'mashed', 0, 'low', 0),
('r020', 'Rolled oats', 1.5, 'cup', NULL, 0, 'low', 1),
('r020', 'Peanut butter', 0.25, 'cup', NULL, 0, 'low', 2),
('r020', 'Dark chocolate chips', 2, 'tbsp', NULL, 1, 'low', 3);

INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES
('r001', 1, 'Whisk the eggs with a pinch of salt and pepper.'),
('r001', 2, 'Heat garlic-infused oil in a non-stick pan over medium heat and wilt the spinach for 1 minute.'),
('r001', 3, 'Pour in the eggs, tilt to coat, and cook until almost set.'),
('r001', 4, 'Crumble the feta over one half, fold and slide onto a plate.'),
('r002', 1, 'Combine oats, lactose-free milk and yoghurt in a jar.'),
('r002', 2, 'Stir, seal and refrigerate overnight (at least 6 hours).'),
('r002', 3, 'In the morning top with blueberries, sliced strawberries and a drizzle of maple syrup.'),
('r003', 1, 'Mash the banana, then whisk in the egg and lactose-free milk.'),
('r003', 2, 'Fold in the buckwheat flour and baking powder until just combined.'),
('r003', 3, 'Cook 1/4-cup portions on a greased pan over medium heat, flipping when bubbles form.'),
('r003', 4, 'Serve warm with maple syrup.'),
('r004', 1, 'Cook the quinoa in plenty of water for 12-15 minutes, then drain and cool.'),
('r004', 2, 'Finely dice the tomato and cucumber and chop the herbs.'),
('r004', 3, 'Whisk lemon juice with olive oil, salt and pepper.'),
('r004', 4, 'Toss everything together and chill before serving.'),
('r005', 1, 'Cook the jasmine rice according to packet directions.'),
('r005', 2, 'Slice the chicken, toss with garlic-infused oil and soy sauce.'),
('r005', 3, 'Grill or pan-fry the chicken until cooked through, about 6-8 minutes.'),
('r005', 4, 'Serve over rice with carrot and a scatter of green spring-onion tops.'),
('r006', 1, 'Layer sliced tomato and mozzarella over the rice cakes.'),
('r006', 2, 'Top with torn basil and a drizzle of olive oil, salt and pepper.'),
('r007', 1, 'Preheat oven to 200C (400F).'),
('r007', 2, 'Place salmon on lined tray, drizzle with garlic-infused oil and season.'),
('r007', 3, 'Top with lemon slices and dill, then bake 15-18 minutes until flaky.'),
('r008', 1, 'Cook the jasmine rice according to packet directions.'),
('r008', 2, 'Sear the beef strips in a hot wok for 2 minutes, then set aside.'),
('r008', 3, 'Stir-fry carrot, capsicum and ginger for 3 minutes, then add bok choy.'),
('r008', 4, 'Return beef, add soy sauce, toss for 1 minute and serve over rice.'),
('r009', 1, 'Preheat oven to 200C and roast zucchini, capsicum and cherry tomato with garlic-infused oil for 25-30 minutes.'),
('r009', 2, 'Cook polenta in salted water, stirring, until thick and creamy.'),
('r009', 3, 'Spoon polenta into bowls, top with roast veg and grated parmesan.'),
('r010', 1, 'Mix oats, peanut butter and maple syrup in a bowl.'),
('r010', 2, 'Fold in the chocolate chips.'),
('r010', 3, 'Roll into 12 bite-sized balls and refrigerate 30 minutes to firm up.'),
('r011', 1, 'Cut carrot and cucumber into sticks.'),
('r011', 2, 'Stir lemon juice and chives into the yoghurt and season to taste.'),
('r011', 3, 'Serve the veg sticks with the dip alongside.'),
('r012', 1, 'Melt the dark chocolate gently over a double boiler or in short microwave bursts.'),
('r012', 2, 'Spread onto a lined tray, scatter strawberries and a pinch of sea salt.'),
('r012', 3, 'Chill until set, then break into shards.'),
('r013', 1, 'Whisk eggs with the lactose-free milk, salt and pepper.'),
('r013', 2, 'Toast the sourdough.'),
('r013', 3, 'Cook eggs gently over low heat, stirring, until just set.'),
('r013', 4, 'Pile onto the toast and scatter with chives.'),
('r014', 1, 'Stir chia seeds, lactose-free milk and maple syrup together in a jar.'),
('r014', 2, 'Refrigerate overnight (or at least 4 hours), stirring once after 10 minutes.'),
('r014', 3, 'Top with blueberries and sliced strawberries before serving.'),
('r015', 1, 'Cook the rice vermicelli, drain and cool. Pan-fry the tofu strips until golden.'),
('r015', 2, 'Soften one rice paper sheet in warm water for 10 seconds.'),
('r015', 3, 'Layer tofu, carrot, cucumber, mint and noodles, then roll up tightly.'),
('r015', 4, 'Repeat and serve with tamari for dipping.'),
('r016', 1, 'Preheat oven to 180C (350F). Whisk the eggs and season.'),
('r016', 2, 'Heat garlic-infused oil in an oven-proof pan, wilt the spinach, add roast pumpkin.'),
('r016', 3, 'Pour in the eggs, scatter feta and spring-onion tops.'),
('r016', 4, 'Bake 20-25 minutes until set, then slice into 4.'),
('r017', 1, 'Preheat oven to 200C (400F).'),
('r017', 2, 'Toss chicken, potatoes, lemon and rosemary with garlic-infused oil and seasoning.'),
('r017', 3, 'Spread on a tray and roast 40-45 minutes until golden and cooked through.'),
('r018', 1, 'Cook the jasmine rice according to packet directions.'),
('r018', 2, 'Stir-fry ginger in garlic-infused oil, add zucchini for 3 minutes.'),
('r018', 3, 'Add prawns and soy sauce, cook until prawns turn pink (3-4 minutes).'),
('r018', 4, 'Serve over the rice.'),
('r019', 1, 'Preheat oven to 200C (400F).'),
('r019', 2, 'Toss carrots with olive oil, maple syrup, thyme, salt and pepper.'),
('r019', 3, 'Roast 25-30 minutes, turning once, until caramelised.'),
('r020', 1, 'Preheat oven to 180C (350F) and line a tray.'),
('r020', 2, 'Mix mashed banana, oats and peanut butter; fold in chocolate chips.'),
('r020', 3, 'Spoon 12 mounds onto the tray and flatten slightly.'),
('r020', 4, 'Bake 12-15 minutes until golden at the edges.');

INSERT INTO recipe_tags (recipe_id, tag) VALUES
('r001', 'vegetarian'), ('r001', 'high-protein'), ('r001', 'quick'), ('r001', 'gluten-free'),
('r002', 'vegetarian'), ('r002', 'make-ahead'), ('r002', 'gluten-free'),
('r003', 'vegetarian'), ('r003', 'gluten-free'), ('r003', 'kid-friendly'),
('r004', 'vegan'), ('r004', 'gluten-free'), ('r004', 'meal-prep'),
('r005', 'high-protein'), ('r005', 'gluten-free'), ('r005', 'meal-prep'),
('r006', 'vegetarian'), ('r006', 'quick'), ('r006', 'no-cook'),
('r007', 'high-protein'), ('r007', 'gluten-free'), ('r007', 'omega-3'),
('r008', 'high-protein'), ('r008', 'gluten-free'), ('r008', 'family'),
('r009', 'vegetarian'), ('r009', 'gluten-free'),
('r010', 'vegetarian'), ('r010', 'no-bake'), ('r010', 'snack'),
('r011', 'vegetarian'), ('r011', 'gluten-free'), ('r011', 'no-cook'),
('r012', 'vegetarian'), ('r012', 'gluten-free'), ('r012', 'no-bake'),
('r013', 'vegetarian'), ('r013', 'high-protein'), ('r013', 'quick'),
('r014', 'vegetarian'), ('r014', 'gluten-free'), ('r014', 'make-ahead'), ('r014', 'no-cook'),
('r015', 'vegan'), ('r015', 'gluten-free'), ('r015', 'no-cook'),
('r016', 'vegetarian'), ('r016', 'gluten-free'), ('r016', 'high-protein'), ('r016', 'meal-prep'),
('r017', 'high-protein'), ('r017', 'gluten-free'), ('r017', 'family'), ('r017', 'one-pan'),
('r018', 'high-protein'), ('r018', 'gluten-free'), ('r018', 'quick'),
('r019', 'vegan'), ('r019', 'gluten-free'), ('r019', 'side'),
('r020', 'vegetarian'), ('r020', 'gluten-free'), ('r020', 'kid-friendly'), ('r020', 'no-bake');
`;
